language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: unifiprojects
    token: 
      secure: $SONAR_TOKEN

install: true

cache:
  directories:
    - $HOME/.sonar/cache

script:
- ./mvnw clean verify -Pjacoco
- ./mvnw coveralls:report sonar:sonar