language: java

addons:
  sonarcloud:
    organization: unifiprojects
    token: 
      secure: $SONAR_TOKEN

services:
  - docker

matrix:
  include:
    # perform code coverage, send report to coveralls and execute sonar
    - jdk: openjdk8
      if: type IN (push)
      env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
    # perform also mutation testing, but only on Pull Request
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Ppit,jacoco coveralls:report sonar:sonar"
    # active docker in integration-mysql branch
    - jdk: openjdk8
      if: branch = integration-mysql
      env: MAVEN_ARGS="-Pjacoco,docker coveralls:report sonar:sonar"
          
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
- ./mvnw clean verify $MAVEN_ARGS