language: java

addons:
  sonarcloud:
    organization: unifiprojects
    token: 
      secure: $SONAR_TOKEN

matrix:
  include:
    - jdk: openjdk8
      if: type IN (push)
      env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
      if: branch = rest-authentication
      env: MAVEN_ARGS="-Pjacoco-restcontroller coveralls:report sonar:sonar"      
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Ppit,jacoco coveralls:report sonar:sonar"

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
- ./mvnw clean verify $MAVEN_ARGS