language: java

addons:
  sonarcloud:
    organization: unifiprojects
    token: 
      secure: $SONAR_TOKEN

services:
  - mysql

matrix:
  include:
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Pe2e"
   
install: skip

env:
    
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - ./mvnw clean verify $MAVEN_ARGS