language: java
addons:
  sonarcloud:
    organization: unifiprojects
    token:
      secure: $SONAR_TOKEN
matrix:
  include:
  - jdk: openjdk8
    if: type IN (pull_request) AND type NOT IN (push)
    env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar"
  - jdk: openjdk8
    if: type IN (push)
    env: MAVEN_ARGS="-Pjacoco,it coveralls:report sonar:sonar"
  - jdk: openjdk8
    if: type IN (push)
    env: MAVEN_ARGS="-Pe2e"
  - jdk: openjdk8
    if: type IN (push)
    env: MAVEN_ARGS="-Ppit"
services:
- docker
- xvfb
install: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
script:
- ./mvnw clean verify $MAVEN_ARGS