language: java

addons:
  sonarcloud:
    organization: unifiprojects
    token: 
      secure: $SONAR_TOKEN

services:
  - docker
  - xvfb

matrix:
  include:
    - jdk: openjdk8
      if: type IN (pull_request)
      env: MAVEN_ARGS="-Pe2e"
   
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - travis_wait 20 ./mvnw clean verify $MAVEN_ARGS